[2022-09-25T14:16:03.293+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: ELT_dag.create_table manual__2022-09-25T14:15:45.328532+00:00 [queued]>
[2022-09-25T14:16:04.074+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: ELT_dag.create_table manual__2022-09-25T14:15:45.328532+00:00 [queued]>
[2022-09-25T14:16:04.074+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-09-25T14:16:04.074+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2022-09-25T14:16:04.074+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-09-25T14:16:04.238+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_table> on 2022-09-25 14:15:45.328532+00:00
[2022-09-25T14:16:04.243+0000] {standard_task_runner.py:54} INFO - Started process 616 to run task
[2022-09-25T14:16:04.246+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ELT_dag', 'create_table', 'manual__2022-09-25T14:15:45.328532+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/ELT_dag.py', '--cfg-path', '/tmp/tmpg4qc_w8t']
[2022-09-25T14:16:04.247+0000] {standard_task_runner.py:83} INFO - Job 3: Subtask create_table
[2022-09-25T14:16:04.249+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/ELT_dag.py
[2022-09-25T14:16:57.576+0000] {timeout.py:68} ERROR - Process timed out, PID: 616
[2022-09-25T14:17:02.837+0000] {dagbag.py:330} ERROR - Failed to import: /opt/***/dags/ELT_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ELT_dag.py", line 10, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/api.py", line 48, in <module>
    from pandas.core.groupby import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/groupby/generic.py", line 64, in <module>
    from pandas.core.aggregation import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/aggregation.py", line 33, in <module>
    from pandas.core.indexes.api import Index
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexes/api.py", line 19, in <module>
    from pandas.core.indexes.datetimes import DatetimeIndex
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexes/datetimes.py", line 62, in <module>
    from pandas.core.indexes.datetimelike import DatetimeTimedeltaMixin
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 872, in get_code
  File "<frozen importlib._bootstrap_external>", line 959, in _cache_bytecode
  File "<frozen importlib._bootstrap_external>", line 984, in set_data
  File "<frozen importlib._bootstrap_external>", line 112, in _write_atomic
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/***/dags/ELT_dag.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://***.apache.org/docs/apache-***/2.4.0/best-practices.html#top-level-python-code
* https://***.apache.org/docs/apache-***/2.4.0/best-practices.html#reducing-dag-complexity, PID: 616
[2022-09-25T14:17:10.473+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 3 for task create_table (Dag 'ELT_dag' could not be found; either it does not exist or it failed to parse.; 616)
[2022-09-25T14:17:11.002+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-09-25T14:17:11.564+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
